    language: php
    php:
    - 5.4
    - 5.5
  
    before_script:
    - mkdir data/cache
    - chmod 777 data/cache
    - composer self-update
    - composer install
     
    script: phpunit -c tests
